baseURL = "/"
relativeURLs = true
languageCode = "en-gb"
title = "Home"

[permalinks]
  blog = "/blog/:slug/"

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    style = "catppuccin-latte"
    lineNos = true